# Site settings
title: Great New Blog Title
author: 
  name: Raul Palma
  email: raul-email@domain.com
description: "Great site about Jekyll on GH-Pages."

# Build settings
remote_theme: jekyll/minima
